### ISSUE TITLE
IDA Pro warning when downloading from CLI

### ISSUE THREAD

**Issue by vidalattias** [quarkslab/diffing_obfuscation_dataset#2]
Thank you for this repo.

When trying to download from the cli command `obfu-dataset-cli download-all -r dataset`, I obtain the following warning

`WARNING:root:IDA Pro executable not found, should be in $PATH or IDA_PATH env variable`

I think you should specify in the README that IDA Pro is expected to be installed on the machine and the supported version.

Thanks again!

**Comment by RobinDavid** [comment]
Hello @vidalattias.

Thanks for pointing this out. In fact we do not require IDA to download the dataset. We left an import of ``idascript`` that we do not even use. I just removed it: https://github.com/quarkslab/diffing_obfuscation_dataset/commit/a038f84d158d426ccc75a9df22b2d8013bf8b841

Please note that we are going to push new versions of zip packages to also embbed the ground-truth for every binary (to know exactly which functions have been obfuscated and how).

*(Let's keep the issue open. I'll let you know when updated.)*

**Comment by roxanecohen** [comment]
Hello @vidalattias, 
We finally updated new zip files with modified ground-truth and you can now download the files. If you encounter any other bug or errors, please let us know.
