### ISSUE TITLE
Typo in the README

### ISSUE THREAD

**Issue by vidalattias** [quarkslab/diffing_obfuscation_dataset#3]
In the README, in section "Detailed description", you say

> Example. The binary "dataset/zlib/obfuscated/tigress/CFF/50/zlib_tigress_gcc_x64_CFF_50_1_O0.exe" indicates that the project zlib was obfuscated using Tigress with a intra-procedural obfuscation that flattens the controlflow. 50% of the functions are obfuscated and the seed is set to 3.

I guess you mean "the seed is set to 1" ?

If I understand well, a file has the format {program}_{obfuscation}_{compiler}_{arch}_{obfuscation}_{obfuscation_level}_{seed}_{compiler_optimization}.exe ?
With compiler=gcc and arch=x64 for now?

If so, I think it would be nice if it was laid down in a more explicit way higher in the README, it might be an important step for people that would want to have a quick understanding of your file ordering.

Thank you!

**Comment by RobinDavid** [comment]
Thanks for the feedback.

We tried to make it more explicit in this commit: https://github.com/quarkslab/diffing_obfuscation_dataset/commit/55f69c453d906040544625387fb09e30b2c0d1ba
